
production:
  clients:
    default:
      database: hungerstruck
      hosts:
        - localhost:27017
    enviark:
      database: enviark
      hosts:
        - localhost:27017 # will be separate eventually
development:
  clients:
    default:
      database: hungerstruck_development
      hosts:
        - localhost:27017
    enviark:
      database: enviark
      hosts:
        - localhost:27017
