
production:
  clients:
    default:
      database: hungerstruck
      hosts:
        - localhost:27017
    enviark:
      database: enviark
      hosts:
        - localhost:27017 # will be separate eventually
  options:
    belongs_to_required_by_default: false
development:
  clients:
    default:
      database: hungerstruck_development
      hosts:
        - localhost:27017
    enviark:
      database: enviark
      hosts:
        - localhost:27017
  options:
    belongs_to_required_by_default: false
